AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: S3 Object Compression Lambda Function

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name for naming resources
    AllowedValues:
      - dev
      - staging
      - prod

  S3BucketName:
    Type: String
    Description: Name of the S3 bucket for object compression
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    ConstraintDescription: Must be a valid S3 bucket name

Globals:
  Function:
    Timeout: 300
    MemorySize: 1024
    Tracing: Active

Resources:
  # S3 Bucket for storing objects and compressed files
  S3ZipperBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-s3-zipper-bucket
        - Key: Environment
          Value: !Ref EnvironmentName

  # Lambda Execution Role
  S3ZipperLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3BucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub 'arn:aws:s3:::${S3BucketName}'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-lambda-role

  # Lambda S3 Invocation Permission (managed automatically by SAM Events)

  # Lambda Function using container image
  S3ZipperFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
    Properties:
      FunctionName: !Sub ${EnvironmentName}-s3-zipper-function
      PackageType: Image
      Role: !GetAtt S3ZipperLambdaRole.Arn
      EphemeralStorage:
        Size: 10240
      Environment:
        Variables:
          LOG_LEVEL: INFO
      Events:
        S3ObjectCreated:
          Type: S3
          Properties:
            Bucket: !Ref S3ZipperBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
      Tags:
        Name: !Sub ${EnvironmentName}-s3-zipper-function
        Environment: !Ref EnvironmentName

  # Lambda Function Version (for rollback capability)
  # (Removed) Lambda Function Version to avoid cycles during S3 event wiring

  # Lambda Function Alias for easy version management
  # (Removed) Lambda Function Alias to avoid cycles

  # CloudWatch Log Group
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${EnvironmentName}-s3-zipper-function
      RetentionInDays: 30

  # (Removed) CloudWatch Alarm for Lambda Errors to avoid cycles

  # (Removed) CloudWatch Alarm for Lambda Duration to avoid cycles

  # S3 Bucket Notification
  # S3 Bucket Notification role not required; events configured on function

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket for object compression
    Value: !Ref S3ZipperBucket
    Export:
      Name: !Sub ${AWS::StackName}-S3BucketName

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt S3ZipperFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaFunctionArn

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref S3ZipperFunction
    Export:
      Name: !Sub ${AWS::StackName}-LambdaFunctionName

  # (Removed) Lambda version outputs
